# 应用端口
spring:
  application:
    # 应用名称
    name: provider-user
#  cloud:
#    label: master
#    name: user
#    profile: dev
#    uri: http://localhost:8888/
  
# eureka 配置
eureka:
  client:
    serviceUrl:
      defaultZone: http://jorian:123456@localhost:8761/eureka
 
logging:
  level:
    root: INFO
